### PR TITLE
Add age related variables

### PR DESCRIPTION
**Pull request by andersonfrailey**
This PR adds the age variables used in UBI calculations, makes a couple PEP8 fixes, and comments out the lines of code used to create CSV's at each step in the process to make everything run a touch faster.

@hdoupe give it a look and let me know if it's good to merge.

### CODE REVIEW

**Comment by hdoupe** [comment]
@andersonfrailey there's another regex statement that needs to be altered in add_nonfilers.py.  Besides that, it looks good.

**Comment by andersonfrailey** [comment]
@hdoupe good catch. Latest commit fixes the regex statement in `add_nonfilers.py`.

**Comment by hdoupe** [comment]
@andersonfrailey, I made the same mistake yesterday when I was trying to find where the age variables were removed.  This should be ready to merge.

**Comment by andersonfrailey** [comment]
@hdoupe thanks for the review. Merging.

**Pull request merged**
